development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "un_secreto_local_cualquiera" %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "otro_secreto_local_cualquiera" %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
