import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS } from '../../styles/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgLight,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 100,
  },
  headerSection: {
    backgroundColor: COLORS.primary, // Davivienda red base
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ? StatusBar.currentHeight + 60 : 85) : 80,
    paddingHorizontal: 20,
    paddingBottom: 70,
    position: 'relative',
    overflow: 'hidden',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  gradientOverlay1: {
    position: 'absolute',
    top: -80,
    right: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: COLORS.bgRedGlow,
    opacity: 0.25,
  },
  gradientOverlay2: {
    position: 'absolute',
    bottom: -100,
    left: -80,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: COLORS.bgRedDark,
    opacity: 0.45,
  },
  gradientOverlay3: {
    position: 'absolute',
    bottom: -10,
    right: -20,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: COLORS.bgRedMedium,
    opacity: 0.4,
  },
  headerContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 10,
  },
  headerWelcomeCol: {
    flex: 1,
    paddingRight: 10,
  },
  welcomeTextLabel: {
    fontSize: 26,
    fontWeight: '800',
    color: COLORS.textWhite,
    lineHeight: 30,
  },
  welcomeTextName: {
    fontSize: 26,
    fontWeight: '800',
    color: COLORS.textWhite,
    lineHeight: 30,
    marginBottom: 6,
  },
  phoneText: {
    fontSize: 12,
    color: '#FEE2E2',
    opacity: 0.9,
  },
  logoCol: {
    width: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoRoundedBadge: {
    width: 82,
    height: 56,
    borderRadius: 14,
    backgroundColor: COLORS.cardBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.cardBg,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  headerLogoImageRight: {
    width: 68,
    height: 40,
  },
  balanceCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 24,
    marginHorizontal: 16,
    marginTop: -25, // Overlaps the red banner
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
      },
      android: {
        elevation: 4,
      },
    }),
    zIndex: 20,
  },
  balanceLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textLight,
    marginBottom: 6,
  },
  balanceValue: {
    fontSize: 32,
    fontWeight: '900',
    color: COLORS.valueBurgundy,
    textAlign: 'center',
    marginBottom: 6,
  },
  balanceCurrency: {
    fontSize: 13,
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  menuGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 20,
  },
  gridButton: {
    flex: 0.485,
    backgroundColor: COLORS.cardBg,
    borderRadius: 24,
    paddingVertical: 22,
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  redIconContainer: {
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  arrowsRow: {
    flexDirection: 'row',
    marginBottom: -4,
  },
  arrowText: {
    color: COLORS.primary,
    fontSize: 26,
    fontWeight: 'bold',
  },
  billOutline: {
    width: 38,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.cardBg,
  },
  billCircle: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1.8,
    borderColor: COLORS.primary,
  },
  historyRow: {
    position: 'relative',
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  documentSheet: {
    width: 26,
    height: 32,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: COLORS.primary,
    padding: 4,
    justifyContent: 'space-between',
    backgroundColor: COLORS.cardBg,
  },
  docLine: {
    height: 2,
    backgroundColor: COLORS.primary,
    borderRadius: 1,
  },
  smallClock: {
    position: 'absolute',
    bottom: 2,
    right: 0,
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.cardBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clockHand: {
    width: 4,
    height: 4,
    borderLeftWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: COLORS.primary,
    transform: [{ rotate: '45deg' }],
  },
  gridButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.valueBurgundy,
    lineHeight: 18,
    textAlign: 'center',
  },
  logoutContainer: {
    alignSelf: 'center',
    marginTop: 44, // Pushed further down
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    borderRadius: 22,
    backgroundColor: 'transparent',
  },
  logoutText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  bottomTabBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    backgroundColor: COLORS.cardBg,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: Platform.OS === 'ios' ? 15 : 0,
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  tabIconHome: {
    width: 22,
    height: 20,
    alignItems: 'center',
  },
  tabIconHomeRoof: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: COLORS.primary,
  },
  tabIconHomeBody: {
    width: 16,
    height: 10,
    backgroundColor: COLORS.primary,
    position: 'relative',
    marginTop: -1,
  },
  tabIconLock: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 2,
  },
  tabIconLockShackle: {
    width: 10,
    height: 8,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: COLORS.textLight,
    borderBottomWidth: 0,
    marginBottom: -1,
  },
  tabIconLockBody: {
    width: 14,
    height: 9,
    borderRadius: 1.5,
    backgroundColor: COLORS.textLight,
  },
  tabIconHelp: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: COLORS.textLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabIconHelpText: {
    color: COLORS.textLight,
    fontSize: 11,
    fontWeight: 'bold',
    lineHeight: 12,
    textAlign: 'center',
  },
  tabTextActive: {
    fontSize: 10,
    color: COLORS.primary,
    fontWeight: '700',
    marginTop: 3,
  },
  tabText: {
    fontSize: 10,
    color: COLORS.textLight,
    fontWeight: '600',
    marginTop: 3,
  },
});
